package FileGeneration;

import java.awt.Desktop;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Date;

import BicyclePartDistributorshipAPI.Controllers.InvoiceController;
import BicyclePartDistributorshipAPI.Models.InvoiceSaleRecord;
import Main.APICaller;

public class PaycheckTXTGenerator implements IPaycheckGenerator {

	@Override
	public void generatePaycheck(String associate, Instant beginDate, Instant endDate) throws IOException {
		ArrayList<InvoiceSaleRecord> records = new ArrayList<>();
    	for(InvoiceController controller : APICaller.getInvoiceControllerList()) {
    		records.addAll(controller.getSaleRecordList());
    	}
    	records.removeIf(r -> !r.getSalesAssociate().equals(associate));
    	records.removeIf(r -> r.getDatetime().toInstant().isBefore(beginDate));
    	records.removeIf(r -> r.getDatetime().toInstant().isAfter(endDate));
    	
    	String filepath = "Output/Paychecks/" + associate + "-" + Instant.now().toEpochMilli() + ".txt";
    	
    	try(FileWriter writer = new FileWriter(filepath)) {
    		SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
    		writer.write("Paycheck for " + associate + "\n");
    		writer.write("Generated by " + APICaller.getLoggedInUser() + " @ " + format.format(new Date()));
    		for(InvoiceSaleRecord record : records) {
    			writer.write(record.getPartNumber() + " " + record.getQuantity() + " " + 
    						 format.format(record.getDatetime()) + "\n");
    		}
    		
    		if(Desktop.isDesktopSupported()) {
    			new Thread(() -> {
    				try {
						Desktop.getDesktop().open(new File(filepath));
					} catch (IOException e) {
						//
					}
    			}).start();
    		}
    	}
	}
}
